### ISSUE TITLE
[JOSS-Paper] comparison to the state of the field

### ISSUE THREAD

**Issue by Yurlungur** [Sbozzolo/kuibit#12]
Overall the paper reads quite well. One thing I noticed is that there is not much comparison to other visualization and analysis tools. For example, how does kuibit compare to visit, yt, or even pycactus? It may also be enough to mention that many users of the Einstein Toolkit write their own visualization pipelines by hand.

**Comment by Sbozzolo** [comment]
Thanks, I added a paragraph surveying the alternatives.

You can find the diff here: https://github.com/Sbozzolo/kuibit/compare/joss-paper?expand=1

**Comment by Yurlungur** [comment]
Thanks. That looks great!
