### ISSUE TITLE
A question on developing with poetry?

### ISSUE THREAD

**Issue by Yurlungur** [Sbozzolo/kuibit#15]
I know poetry isn't yours---it's essentially a dependency. But from skimming Poetry's documentation, and yours, one thing isn't clear to me, which might be worth highlighting in the documentation.

When I develop a python package---e.g., yt---with a traditional `setup.py` build system, I can call
```python
python setup.py develop --user
```
to tell it to create symlinks to the python code so that when I import a module from anywhere, if I modify the code in the repo, the changes are reflected in the import. Is the same true here? i.e., do I have to do anything special in poetry to enable this kind of behaviour?

**Comment by Sbozzolo** [comment]
This is a long-standing question/issue with poetry (https://github.com/python-poetry/poetry/issues/34). I think that now it is possible to install a package in editable mode (once I managed to get it to work), but I cannot tell you exactly how to do it.

`poetry` installs a virtualenv in `~/.cache/pypoetry/*/virtualenvs` (at least on GNU/Linux). My personal development workflow is to activate that environment directly or to use `poetry shell`. Note that once you are in the `poetry shell` you can freely move around your filesystem, the experience is quite similar to installing a package in development mode.

**Comment by Yurlungur** [comment]
Ah ok. Cool. That works, then. It might be nice to add a comment about activating the environment directly in your documentation.

**Comment by Sbozzolo** [comment]
Done! d64525426564660b11c317cb46fd6fc588331ebb
