### ISSUE TITLE
naming convention derived vs differentiated

### ISSUE THREAD

**Issue by Yurlungur** [Sbozzolo/kuibit#17]
Why are the methods for differentiating a time series called `derived`? Would differentiate not be more appropriate?

**Comment by Sbozzolo** [comment]
Thanks for catching this! It might have been I started at the very beginning with using `derivative`, then I established the convention about method names, and I had to make it a verb, and `derived` came to be (which as a non-native speaker I accepted).

I'll fix this.

**Comment by Sbozzolo** [comment]
Fixed in e4a8d17d0ca8a86d02dcceeb6588ea4392c807f0
