### ISSUE TITLE
One-line change to fix bug in mask_removed()

### ISSUE THREAD

**Issue by ekwessel** [Sbozzolo/kuibit#28]
Calling mask_removed() on a masked series removes the masked points, but calling is_masked() on the resulting series still returns True. The problem is that the x and y arrays are still MaskedArrays, to fix this they should be converted to standard ndarrays.

My fork of kuibit is both ahead and behind by dozens of commits, and making a special branch with just the relevant commit is too much of a hassle for this minor issue, so rather than creating a pull request I'm just going to explain the edit that should be done:

To fix, change line 673 of series.py to:

`return type(self)(np.ma.compressed(self.x[mask]), np.ma.compressed(self.y[mask]), True)`

**Comment by Sbozzolo** [comment]
Thanks! Fixed in `next`.
