### ISSUE TITLE
ET sensitivity curve is outdated

### ISSUE THREAD

**Issue by bgiacoma** [Sbozzolo/kuibit#33]
It seems to me that Kuibit uses the ET-B sensitivity curve for the Einstein Telescope. I was informed by Tim Dietrich that this sensitivity curve is outdated. People should use the ET-D. These are the relevant information on the new sensitivity curve for ET:

- This is the paper with the discussion of ET-D and its differences with the older versions ET-B and ET-C: https://arxiv.org/pdf/1012.0908.pdf
- The link to the noise curves is here https://www.et-gw.eu/etsensitivities (the link is also given in the paper).

**Comment by Sbozzolo** [comment]
Thanks, sensitivity curve added in c164adc28038a7e183ce3c36a9ea6aa0d1c215c9.
