### ISSUE TITLE
MOPI version constraint inquiry

### ISSUE THREAD

**Issue by irrationalnumbers** [Sbozzolo/kuibit#35]
Hi Gabriele,
Out of curiosity, is there a specific reason to continue to restrict the version of mopi to <0.3 even in the current development version?  I usually run the latest version which is technically in conflict with kuibit versioning requirements and haven't had any issues so far, but wanted to ask in case there are edge cases that I might need to be concerned with.

Thanks!
Samuel

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kuibit 1.4.0.dev2 requires motionpicture<0.3.0,>=0.2.0, but you have motionpicture 0.3.1 which is incompatible.

**Comment by Sbozzolo** [comment]
Thanks, I learned something new about Poetry

Fixed in f0c79fcd

**Comment by irrationalnumbers** [comment]
Oy, I wouldn't have guessed it would be a notation difference.  Nice find
